### ISSUE TITLE
Computer freezes using IMAQ

### ISSUE THREAD

**Issue by aromanillos** [AlexShkarin/pyLabLib-v0#3] opened 2021-01-26 17:14 UTC
Hello, maybe is not a problem with the module itself, but could be that the module could prevent this.

I am using the IMAQ module for acquiring continuous frames from my camera. for both displaying and saving. I am doing long recordings and normally I am able to save around 20k-30k frames( at 20-30fps) with no problem. However, it happened sometimes already that during acquisition the computer just freezes and nothing can be done in the computer. I display the output in a console, but nothing is reflected/printed when this happens. It has maybe something to do with the buffer size/ IMAQ library?

I am using a producer-consumer pattern, this is the acquisition part:

```
from pylablib.aux_libs.devices import IMAQ,IMAQdx
        def producer(self,q,q2,fpsval):
        
                self.camera.setup_acquisition(True,250)
                self.camera.start_acquisition()
                print(fpsval)
                while self.record is True:
                    self.camera.wait_for_frame(timeout=20.)
                    rng=self.camera.get_new_images_range()
                    frames=self.camera.read_multiple_images(rng,missing_frame='zeros')
                    timestamps=(np.arange(rng[0],rng[1]+1)/fpsval)*1e6
                    q2.put(frames[0])
                    if self.save is True:                        
                        q.put((frames,timestamps))                        
                    del frames,timestamps
                print('None')
                q.put((None,None))
```
being self.camera= IMAQ.IMAQCamera(name='img0') 

thank you in advance

**Comment by AlexShkarin** [comment] 2021-01-26 17:27
Hello!

It looks like your PC is running out of RAM. It can happen, if you place the frames into the queue (``q`` and ``q2``), but don't extract them, extract them at lower rate, or store them somewhere else in memory after extraction. You can verify it by monitoring the memory used by the Python process in the Task Manager: if it keeps going up steadily (judging by your numbers, at a rate of about ~10MB/s), then this is the problem.

**Comment by AlexShkarin** [comment] 2021-02-13 23:21
Hello!

Were you able to look more into the issue? Is it indeed a RAM problem, or does it look like something else?
In my experience, I've been able to keep the continuous acuqistion running for hours at least at ~5-10kFPS, but it was only tested on a couple of different PCs, and a specific camera (PhotonFocus MV1) and frame grabbers (NI PCIe-1430 or 1433). So if you are experiencing problems with different hardware, I would be really interested to know if there is indeed a problem with the library.

**Comment by aromanillos** [comment] 2021-02-13 23:33
hello Alex,

I did not have the issue again, but I have been monitoring the RAM during long acquisitions normally at 20-30fps , but I would like to increase to 50fps I am using NI-PC1437 frame grabber with this camera https://www.princetonirtech.com/products/mvcam. I am doing a producer- double consumer pattern for generating, displaying and saving frames in a not blocking manner. I guess my two queues are generating that increase on RAM. We are actually changing to a 16GB RAM computer so I guess the problem could disappear.

Is there maybe another way to reduce the memory intake during an acquisition using the existing library?

**Comment by AlexShkarin** [comment] 2021-02-16 23:47
Unfortunately, it's hard to say what exactly is going wrong with the code.

**Comment by AlexShkarin** [comment] 2021-02-16 23:52
[Sorry, I misclicked the "Close Issue" button]

Unfortunately, it's hard to say what exactly is going wrong with the code. I could suggest running stress-testing by running a simple single-threaded version where frames are not stored or saved, but are immediately discarded. At the same time, you can monitor the camera buffer fill status to see if it is growing. This should tell you if the issue is related to the PC performance (if the buffer keeps getting filled, so the PC can't catch up with it), or the library (if it still crashes, but the buffer fill level stays constant).

**Comment by aromanillos** [comment] 2021-03-10 18:34
Hello,

We did not see any problem again, so I would say it was indeed the RAM
under certain conditions. I think you can close the issue

best


Adrián Romanillos Botella
m: adrian.romanillos@gmail.com

**Comment by AlexShkarin** [comment] 2021-03-11 21:52
Hello Adrián,

Thank you for the update! I'm closing the issue. Let me know, if it comes up again.

Sincerely,

Alexey.

**Closed by AlexShkarin** 2021-03-11 21:52 UTC
